### PR TITLE
Fix Typescript tutorial headings

### PR DESCRIPTION
**Pull request by Xerus2000**

### CODE REVIEW

**Comment by meganbradley** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/getting-started/tutorial-typescript.md](https://github.com/Xerus2000/cordova-docs-1/blob/patch-1/articles/getting-started/tutorial-typescript.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C24%5C49aab8b9-0baf-5cfb-66e6-0563114d3f57%5CPullRequest%5C201809241611146950-578%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zs%2BNeHFhsfHVV%2Folr4poR%2B%2FLyH%2BRDHJ4gsramYNteng%3D&st=2018-09-24T16%3A07%3A13Z&se=2018-10-25T16%3A12%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by conceptdev** [comment]
I'm really sorry, but the Cordova docs are at a new repo location
https://github.com/MicrosoftDocs/CordovaDocs/issues

It's mentioned in the README, but I know that can be easy to miss. Thanks for taking the time to PR.

**Comment by Xerus2000** [comment]
I would suggest to make the message larger, so it doesn't get overlooked. Maybe even have it be the only thing in the README and then archive the repo, that way it is obvious.

**Comment by conceptdev** [comment]
Yeah, I'm investigating the readonly/archive route now. Apologies again for the confusion.

**Pull request closed without merging**
